version: '3.8'

services:
  deefind:
    build: .
    container_name: deefind
    ports:
      - "1234:1234"
    volumes:
      - /mnt/usbhdd/music/_toTidyUp:/downloads
    environment:
      - DEEZER_ARL=${DEEMIX_ARL}
      - NAVIDROME_URL=${NAVIDROME_URL}
      - NAVIDROME_USER=${NAVIDROME_USER}
      - NAVIDROME_PASS=${NAVIDROME_PASS}
    restart: unless-stopped
